steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/react-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/react-app']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'react-app', '--image', 'gcr.io/$PROJECT_ID/react-app', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']
